### PR TITLE
Create a React boilerplate

### PR DESCRIPTION
**Pull request by LaiqaRafiq**
Create a React boilerplate, so any who starts a new React can copy or start from here

_Originally posted by @MKRNaqeebi in https://github.com/CoalAI/DevOps/issues/9#issuecomment-1247958058

### CODE REVIEW

**Comment by noumandev11** [comment]
@MKRNaqeebi  kindly merge it as soon as possible

**Comment by MKRNaqeebi** [comment]
@LaiqaRafiq I need a demo on this 
CC: @noumandev11

**Comment by noumandev11** [comment]
@LaiqaRafiq  please give demo to @MKRNaqeebi so that i can create new Repo from it

**Comment by LaiqaRafiq** [comment]
I'm available for demo @MKRNaqeebi

**Comment by MKRNaqeebi** [comment]
okay after daily meeting

**Comment by LaiqaRafiq** [comment]
Acknowledged

**Comment by MKRNaqeebi** [comment]
Fix 2 things 

- [ ] 1. Unit tests
- [ ] 2. Pre-commit

CC: @LaiqaRafiq @noumandev11

**Comment by LaiqaRafiq** [comment]
Fixed pre-commit and done unit tests but I'm unable to remove test warnings
@MKRNaqeebi

**Comment by MKRNaqeebi** [comment]
@LaiqaRafiq let me know if you can demo current progress

**Comment by LaiqaRafiq** [comment]
yes I'm available for demo

**Comment by MKRNaqeebi** [comment]
@LaiqaRafiq  call me I am available

**Comment by MKRNaqeebi** [comment]
TODOs:

- [ ] Create one complete component (a component that has almost everything from a real component) and test its every edge case.
- [ ] Use a dummy API from the internet and wrote a unit test to that (you can find APIs online to use).
CC: @LaiqaRafiq @noumandev11

**Comment by LaiqaRafiq** [comment]
Acknowledged

**Review by MKRNaqeebi — CHANGES_REQUESTED** [review]
read last todos

**Pull request merged**
